defaultEntryPoints = ["http", "https"]
[web]
address = ":8081"
[entryPoints]
  [entryPoints.http]
  address = ":8080"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":8443"
    [entryPoints.https.tls]
[acme]
email = "letsencrypt@example.com"
storage = "/etc/letsencrypt/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
